/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import Entity.LoaiMonInf;
import DTO.LoaiMonDto;
import DAO.Connect;
import DAO.LoaiMonDao;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.sql.Blob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phamduc
 */
public class LoaiMonAnJFrame extends javax.swing.JFrame {
     private ArrayList<LoaiMonDto> list;

    private DefaultTableModel model;
     private LoaiMonInf loaiMonInf;

    /**
     * Creates new form LoaiMonAnJFrame
     */
    public LoaiMonAnJFrame() throws RemoteException {
        initComponents();
    this.setLocationRelativeTo(null);
    try {
            loaiMonInf = (LoaiMonInf) Naming.lookup("rmi://localhost:1616/loaiMon");
            System.out.println("Connected to RMI Server");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    list= loaiMonInf.getAll();
    model= (DefaultTableModel) tableLoaiMonAn.getModel();

    showResult();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codeLoaiMon = new javax.swing.JTextField();
        TenLoaiMon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescriptionTA = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableLoaiMonAn = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã loại món");

        jLabel2.setText("Tên loại món");

        DescriptionTA.setColumns(20);
        DescriptionTA.setRows(5);
        jScrollPane1.setViewportView(DescriptionTA);

        tableLoaiMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Tên loại món", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableLoaiMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLoaiMonAnMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableLoaiMonAn);
        if (tableLoaiMonAn.getColumnModel().getColumnCount() > 0) {
            tableLoaiMonAn.getColumnModel().getColumn(0).setMaxWidth(55);
            tableLoaiMonAn.getColumnModel().getColumn(1).setResizable(false);
            tableLoaiMonAn.getColumnModel().getColumn(1).setPreferredWidth(30);
            tableLoaiMonAn.getColumnModel().getColumn(2).setPreferredWidth(40);
            tableLoaiMonAn.getColumnModel().getColumn(3).setResizable(false);
            tableLoaiMonAn.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        jButton1.setText("Cập nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Refresh");

        jLabel3.setText("Mô tả");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2)
                            .addGap(43, 43, 43))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TenLoaiMon, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(codeLoaiMon)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(codeLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TenLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableLoaiMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLoaiMonAnMouseClicked
        // TODO add your handling code here:
       
       int r = tableLoaiMonAn.getSelectedRow();
       String click= (tableLoaiMonAn.getModel().getValueAt(r,1).toString());
        LoaiMonDto dto = null;
         try {
              dto = loaiMonInf.findByCode(click);
         } catch (RemoteException ex) {
             Logger.getLogger(LoaiMonAnJFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
            
            DescriptionTA.setLineWrap(true);
            DescriptionTA.setWrapStyleWord(true);
            DescriptionTA.setText(dto.getDescription());
            codeLoaiMon.setText(dto.getCode());
            TenLoaiMon.setText(dto.getName());
 

    }//GEN-LAST:event_tableLoaiMonAnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        Connect c= new Connect();
//        String code= codeLoaiMon.getText();
//        String sql="UPDATE category_food SET name='"+TenLoaiMon.getText()+"', description = '"+DescriptionTA.getText()+"' WHERE code = '"+code+"'";
//        try{
//            PreparedStatement ps= c.getConnection().prepareStatement(sql);
//            ps.executeUpdate();
//             JOptionPane.showMessageDialog(rootPane,"Cập nhập loại món ăn thành công!");
//             showResult();
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
        String code= codeLoaiMon.getText();
        var name=TenLoaiMon.getText();
        String description=DescriptionTA.getText();
                
         try { 
             loaiMonInf.update(code, name, description);
              JOptionPane.showMessageDialog(rootPane,"Cập nhập loại món ăn thành công!");
              showResult();
         } catch (RemoteException ex) {
             Logger.getLogger(LoaiMonAnJFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoaiMonAnJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoaiMonAnJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoaiMonAnJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoaiMonAnJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LoaiMonAnJFrame().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(LoaiMonAnJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void showResult() throws RemoteException{
        list= loaiMonInf.getAll();
        int rowCount = model.getRowCount();

    // Xóa tất cả các dòng hiện tại trong bảng
    for (int i = rowCount - 1; i >= 0; i--) {
        model.removeRow(i);
    }

    // Thêm lại dữ liệu từ danh sách vào bảng
    int count = list.size();
    for (int i = 1; i <= count; i++) {
        model.addRow(new Object[]{
                i, list.get(i - 1).getCode(), list.get(i - 1).getName(), list.get(i - 1).getDescription(), 
        });
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DescriptionTA;
    private javax.swing.JTextField TenLoaiMon;
    private javax.swing.JTextField codeLoaiMon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableLoaiMonAn;
    // End of variables declaration//GEN-END:variables
}
